name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Aura
      run: |
        chmod +x ./gradlew
        ./gradlew distTar
        mkdir ./src/bot/
        cp ./build/distributions/Aura-*.tar ./src/bot/Aura.tar
    - name: Build and push Docker images
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: aura/aura-bot
        tag: latest
        dockerfile: Dockerfile
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 
      
